Update Project Job Token Scopes
jdalrymple/gitbeaker pull request #3650
Opened 2024-10-30 01:28 UTC by jdalrymple

Now correctly including the group allow lists

fixes #3649

2024-11-05 20:25 UTC, clario-masonb requested changes
Thanks much for working on the update! Just had a note for both of the "add" endpoints, after that I think we'll be solid.

2024-11-05 20:25 UTC, clario-masonb commented on packages/core/src/resources/ProjectJobTokenScopes.ts
> +      endpoint`${projectId}/job_token_scope/groups_allowlist/${targetGroupId}`,
For add, targetGroupId is a post body parameter, not a url parameter 
https://docs.gitlab.com/ee/api/project_job_token_scopes.html#add-a-group-to-a-cicd-job-token-allowlist

the target is only a url parameter for the remove endpoints

2024-11-05 20:25 UTC, clario-masonb commented on packages/core/src/resources/ProjectJobTokenScopes.ts
> +      endpoint`${projectId}/job_token_scope/allowlist/${targetProjectId}`,
For add, targetProjectId is a post body parameter, not a url parameter 
https://docs.gitlab.com/ee/api/project_job_token_scopes.html#add-a-project-to-a-cicd-job-token-inbound-allowlist

the target is only a url parameter for the remove endpoints

2024-11-10 22:51 UTC, merged

2024-11-10 23:09 UTC, jdalrymple commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`41.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/41.2.0) :rocket: